#!/bin/bash

webserverdir=your_webserver_directory
projectlocation=your_git_repo_link
projectname=your_repo_name
automaticpullafter=pull_after

if [ webserverdir == "your_webserver_directory" || projectlocation == "your_git_repo_link" || projectname == "your_repo_name" || automaticpullafter == "pull_after" ]; then
echo "Please set the variables inside the file. Aborting..."
exit
fi

while true; do

git clone $projectlocation

cd $projectname

mv * $webserverdir

rm -rf ../$projectname

cd ~

sleep $automaticpullafter

done


